services:
  cloudflared:
    image: cloudflare/cloudflared:2024.10.0
    command: ["tunnel", "--no-autoupdate", "run", "--token", "${CLOUDFLARE_TUNNEL_TOKEN}"]
    depends_on:
      - api
    restart: unless-stopped
